name = "MonteCarloRadiativeTransfer"
uuid = "6fd93707-527c-4bd4-b333-ba8c36a7f4be"
authors = ["Gabriel Wu <wuzihua@pku.edu.cn> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
